// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Ship_27f5579ed674f391a8bdd06c92936648Index = 0;
		public const int SolarSystem_231ae0877bd5748d18685671ff08a357Index = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Ship_27f5579ed674f391a8bdd06c92936648", 0 },

			{ "SolarSystem_231ae0877bd5748d18685671ff08a357", 1 },

		};
	}
}
