// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Ship_id0_ShipModel_849745348499479206 : ICoherenceComponentData
	{
		public int seed;

		public override string ToString()
		{
			return $"Ship_id0_ShipModel_849745348499479206(seed: {seed})";
		}

		public uint GetComponentType() => Definition.InternalShip_id0_ShipModel_849745348499479206;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _seed_Min = -2147483648;
		private static readonly int _seed_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Ship_id0_ShipModel_849745348499479206)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				seed = other.seed;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(Ship_id0_ShipModel_849745348499479206 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.seed, _seed_Min, _seed_Max, "Ship_id0_ShipModel_849745348499479206.seed");
				data.seed = Coherence.Utils.Bounds.Clamp(data.seed, _seed_Min, _seed_Max);
				bitStream.WriteIntegerRange(data.seed, 32, -2147483648);
			}
			mask >>= 1;
		}

		public static (Ship_id0_ShipModel_849745348499479206, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Ship_id0_ShipModel_849745348499479206();
	
			if (bitStream.ReadMask())
			{
				val.seed = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask, null);
		}
		public static (Ship_id0_ShipModel_849745348499479206, uint, uint?) DeserializeArchetypeShip_27f5579ed674f391a8bdd06c92936648_Ship_id0_ShipModel_849745348499479206_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Ship_id0_ShipModel_849745348499479206();
			if (bitStream.ReadMask())
			{
				val.seed = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Ship_id0_ShipModel_849745348499479206?;
	
		}
	}
}