// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct SolarSystem_id1_SolarSystem_6223684658301783008 : ICoherenceComponentData
	{
		public int seed;
		public int portalCount;

		public override string ToString()
		{
			return $"SolarSystem_id1_SolarSystem_6223684658301783008(seed: {seed}, portalCount: {portalCount})";
		}

		public uint GetComponentType() => Definition.InternalSolarSystem_id1_SolarSystem_6223684658301783008;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _seed_Min = -2147483648;
		private static readonly int _seed_Max = 2147483647;
		private static readonly int _portalCount_Min = -2147483648;
		private static readonly int _portalCount_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (SolarSystem_id1_SolarSystem_6223684658301783008)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				seed = other.seed;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				portalCount = other.portalCount;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(SolarSystem_id1_SolarSystem_6223684658301783008 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.seed, _seed_Min, _seed_Max, "SolarSystem_id1_SolarSystem_6223684658301783008.seed");
				data.seed = Coherence.Utils.Bounds.Clamp(data.seed, _seed_Min, _seed_Max);
				bitStream.WriteIntegerRange(data.seed, 32, -2147483648);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.portalCount, _portalCount_Min, _portalCount_Max, "SolarSystem_id1_SolarSystem_6223684658301783008.portalCount");
				data.portalCount = Coherence.Utils.Bounds.Clamp(data.portalCount, _portalCount_Min, _portalCount_Max);
				bitStream.WriteIntegerRange(data.portalCount, 32, -2147483648);
			}
			mask >>= 1;
		}

		public static (SolarSystem_id1_SolarSystem_6223684658301783008, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new SolarSystem_id1_SolarSystem_6223684658301783008();
	
			if (bitStream.ReadMask())
			{
				val.seed = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.portalCount = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask, null);
		}
		public static (SolarSystem_id1_SolarSystem_6223684658301783008, uint, uint?) DeserializeArchetypeSolarSystem_231ae0877bd5748d18685671ff08a357_SolarSystem_id1_SolarSystem_6223684658301783008_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new SolarSystem_id1_SolarSystem_6223684658301783008();
			if (bitStream.ReadMask())
			{
				val.seed = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.portalCount = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000010;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as SolarSystem_id1_SolarSystem_6223684658301783008?;
	
		}
	}
}